spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret-key: ${JWT_KEY}
  expiration-time-minutes: 15