spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: ${DB_USER}
    password: ${DB_PASS}
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret-key: ${JWT_KEY}
  expiration-time:
    access-token-minutes: 5
    refresh-token-days: 30